class RolesEdit < ActiveRecord::Migration
  def up
	Role.create(:name=> "User",
					:information=> "defaul user",
					:can_add_files=> false,
					:can_delete_files=> false,
					:can_add_news=> false,
					:can_delete_news=> false,
					:can_add_showbill=> false,
					:can_delete_showbill=> false,
					:can_add_history=> false,
					:can_delete_history=> false,
					:can_post_forum=> true,
					:can_admin_forum=> false,
					:can_manage_albums=> false,
					:can_admin_roles=> false,
					:can_edit_news=> false,
					:can_edit_schedule=> false,
					:can_edit_partners=> false,
					:can_edit_custom_pages=> false)
	Role.create(:name=> "Admin",
					:information=> "defaul admin",
					:can_add_files=> true,
					:can_delete_files=> true,
					:can_add_news=> true,
					:can_delete_news=> true,
					:can_add_showbill=> true,
					:can_delete_showbill=> true,
					:can_add_history=> true,
					:can_delete_history=> true,
					:can_post_forum=> true,
					:can_admin_forum=> true,
					:can_manage_albums=> true,
					:can_admin_roles=> true,
					:can_edit_news=> true,
					:can_edit_schedule=> true,
					:can_edit_partners=> true,
					:can_edit_custom_pages=> true)
	Role.create(:name=> "Buned",
					:information=> "defaul buned user",
					:can_add_files=> false,
					:can_delete_files=> false,
					:can_add_news=> false,
					:can_delete_news=> false,
					:can_add_showbill=> false,
					:can_delete_showbill=> false,
					:can_add_history=> false,
					:can_delete_history=> false,
					:can_post_forum=> false,
					:can_admin_forum=> false,
					:can_manage_albums=> false,
					:can_admin_roles=> false,
					:can_edit_news=> false,
					:can_edit_schedule=> false,
					:can_edit_partners=> false,
					:can_edit_custom_pages=> false)
  end

  def down
  end
end
